### ISSUE TITLE
[REQ] Component Request: 

### ISSUE THREAD

**Issue by morwic** [adafruit/Wippersnapper_Components#124] opened 2023-06-01 20:11 UTC
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
INA219

**What type of component is this (i.e.: Pin, I2C)?**
Shunt

**Product URL or Datasheet**
[Add a link to the product's URL or datasheet here.](https://www.adafruit.com/product/904?gclid=CjwKCAjwg-GjBhBnEiwAMUvNWxbTt3rlXnvpFsJiOJyj5QLGqUFJgO3sZ-SaYuT3ZIAemNmNawJZyRoCLZEQAvD_BwE)

**Additional context**
Thank you :)

**Comment by tyeth** [comment] 2023-08-15 14:39
Duplicate of https://github.com/adafruit/Wippersnapper_Components/issues/90
Please subscribe to that issue to be notified when we add the component.

**Closed by tyeth** 2023-08-15 14:39 UTC
Labels: request
