### ISSUE TITLE
[REQ] Component Request: SHT40 

### ISSUE THREAD

**Issue by TheGodMotherG** [adafruit/Wippersnapper_Components#47] opened 2022-05-25 04:56 UTC
**What's the full name of the component you'd like to see in Adafruit.io WipperSnapper?**
The full name of the specific component.

**What type of component is this (i.e.: Pin, I2C)?**
i2c 0x44

**Product URL or Datasheet**
[Add a link to the product's URL or datasheet here.](https://www.adafruit.com/product/4885)

**Additional context**
Best sensor on the market please add support

**Comment by brentru** [comment] 2022-05-25 15:59
Duplicate of https://github.com/adafruit/Wippersnapper_Components/issues/17, closing...

**Closed by brentru** 2022-05-25 15:59 UTC
Labels: request
